name = "SequenceTokenizers"
uuid = "782fbe24-d740-44eb-8e9f-f0831b1cb5e5"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"

[compat]
Optimisers = "0.3"
Functors = "0.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
